//! Engine and builder.
//!
//! The engine owns the registries (connectors, actions, flows) and the
//! persistence handle. Apps build one at startup, register custom
//! connectors and `#[flow_action]` functions, then call `engine.run(name,
//! input)` from their own code paths (HTTP handler, cron job, …) — flows
//! are invoked manually in v1, never auto-triggered by the engine itself.

use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use chrono::Utc;
use serde_json::Value;

use crate::connector::Connector;
use crate::definition::FlowDef;
use crate::error::{FlowError, FlowResult};
use crate::executor::{execute, ExecutorInput};
use crate::persist::{JsonRunStore, RunDoc, RunErrorDoc, RunStore};

/// Action handler stored in the registry. Normalised to a JSON-in / JSON-out
/// async fn so connectors and custom actions look identical to the executor.
pub type ActionFn = Arc<
    dyn Fn(Value) -> Pin<Box<dyn Future<Output = FlowResult<Value>> + Send>>
        + Send
        + Sync,
>;

/// Result of a single flow run as returned to the calling code.
#[derive(Debug, Clone)]
pub struct RunResult {
    pub run_id: String,
    pub flow_name: String,
    pub status: RunStatus,
    pub output: Option<Value>,
    pub error: Option<RunError>,
    pub duration_ms: i64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunStatus {
    Success,
    Failed,
}

/// Structured error returned to the calling code on failure. The `step_id`
/// pinpoints which step blew up and `input` echoes back what it received,
/// so callers can log or surface a precise diagnostic without re-opening
/// the run trace file.
#[derive(Debug, Clone)]
pub struct RunError {
    pub step_id: String,
    pub message: String,
    pub input: Option<Value>,
}

/// Builder used by apps at startup to assemble a `FlowEngine`.
pub struct FlowEngineBuilder {
    connectors: HashMap<String, Arc<dyn Connector>>,
    actions: HashMap<String, ActionFn>,
    flows: HashMap<String, FlowDef>,
    store: Option<Arc<dyn RunStore>>,
}

impl Default for FlowEngineBuilder {
    fn default() -> Self {
        Self {
            connectors: HashMap::new(),
            actions: HashMap::new(),
            flows: HashMap::new(),
            store: None,
        }
    }
}

impl FlowEngineBuilder {
    pub fn new() -> Self { Self::default() }

    pub fn register_connector(&mut self, name: impl Into<String>, c: Arc<dyn Connector>) -> &mut Self {
        self.connectors.insert(name.into(), c);
        self
    }

    /// Register a custom Rust action under `name`. Generated by the
    /// `#[flow_action]` macro; can also be called manually.
    pub fn register_action<F, Fut>(&mut self, name: impl Into<String>, f: F) -> &mut Self
    where
        F: Fn(Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = FlowResult<Value>> + Send + 'static,
    {
        let wrapped: ActionFn = Arc::new(move |v| Box::pin(f(v)));
        self.actions.insert(name.into(), wrapped);
        self
    }

    pub fn register_flow(&mut self, flow: FlowDef) -> &mut Self {
        self.flows.insert(flow.name.clone(), flow);
        self
    }

    pub fn with_store(&mut self, store: Arc<dyn RunStore>) -> &mut Self {
        self.store = Some(store);
        self
    }

    /// Convenience: install a `JsonRunStore` rooted at `dir`.
    pub fn with_json_store(&mut self, dir: impl Into<std::path::PathBuf>) -> FlowResult<&mut Self> {
        let store: Arc<dyn RunStore> = Arc::new(JsonRunStore::new(dir)?);
        self.store = Some(store);
        Ok(self)
    }

    pub fn build(self) -> FlowResult<FlowEngine> {
        let store = self
            .store
            .ok_or_else(|| FlowError::Internal("FlowEngineBuilder needs a RunStore".into()))?;
        Ok(FlowEngine {
            connectors: self.connectors,
            actions: self.actions,
            flows: self.flows,
            store,
        })
    }
}

pub struct FlowEngine {
    connectors: HashMap<String, Arc<dyn Connector>>,
    actions: HashMap<String, ActionFn>,
    flows: HashMap<String, FlowDef>,
    store: Arc<dyn RunStore>,
}

impl FlowEngine {
    pub fn flow_names(&self) -> Vec<String> {
        let mut names: Vec<String> = self.flows.keys().cloned().collect();
        names.sort();
        names
    }

    pub fn get_flow(&self, name: &str) -> FlowResult<&FlowDef> {
        self.flows
            .get(name)
            .ok_or_else(|| FlowError::FlowNotFound(name.to_string()))
    }

    pub fn store(&self) -> Arc<dyn RunStore> {
        self.store.clone()
    }

    /// Trigger a flow with `input` (manual trigger semantics for v1). On
    /// failure, the `RunResult.error` carries a structured diagnostic and
    /// the run trace is still persisted, so callers can surface or log
    /// it precisely.
    pub async fn run(&self, name: &str, input: Value) -> FlowResult<RunResult> {
        self.run_with_trigger(name, input, "manual").await
    }

    pub async fn run_with_trigger(
        &self,
        name: &str,
        input: Value,
        trigger: &str,
    ) -> FlowResult<RunResult> {
        let flow = self.get_flow(name)?.clone();
        let started_at = Utc::now();
        let run_id = uuid::Uuid::new_v4().to_string();

        let exec_input = ExecutorInput {
            flow: &flow,
            run_id: run_id.clone(),
            flow_input: input.clone(),
            connectors: &self.connectors,
            actions: &self.actions,
        };

        let (exec_result, records) = execute(exec_input).await;
        let ended_at = Utc::now();
        let duration_ms = (ended_at - started_at).num_milliseconds();

        match exec_result {
            Ok(output) => {
                let doc = RunDoc {
                    run_id: run_id.clone(),
                    flow_name: name.to_string(),
                    status: "success".into(),
                    trigger_kind: trigger.to_string(),
                    input,
                    output: Some(output.clone()),
                    error: None,
                    started_at,
                    ended_at: Some(ended_at),
                    duration_ms,
                    steps: records,
                };
                self.store.save(&doc).await?;
                Ok(RunResult {
                    run_id,
                    flow_name: name.to_string(),
                    status: RunStatus::Success,
                    output: Some(output),
                    error: None,
                    duration_ms,
                })
            }
            Err(err) => {
                let (step_id, message) = match &err {
                    FlowError::StepFailed { step_id, message } => (step_id.clone(), message.clone()),
                    other => (String::new(), other.to_string()),
                };
                // Partial records are preserved so the failure trace shows
                // exactly which step blew up and what came before it.
                let doc = RunDoc {
                    run_id: run_id.clone(),
                    flow_name: name.to_string(),
                    status: "failed".into(),
                    trigger_kind: trigger.to_string(),
                    input: input.clone(),
                    output: None,
                    error: Some(RunErrorDoc {
                        step_id: step_id.clone(),
                        message: message.clone(),
                        input: Some(input.clone()),
                    }),
                    started_at,
                    ended_at: Some(ended_at),
                    duration_ms,
                    steps: records,
                };
                self.store.save(&doc).await?;
                Ok(RunResult {
                    run_id,
                    flow_name: name.to_string(),
                    status: RunStatus::Failed,
                    output: None,
                    error: Some(RunError { step_id, message, input: Some(input) }),
                    duration_ms,
                })
            }
        }
    }

    /// Replay a previous run by loading its input from the store and
    /// re-executing the flow under the same name.
    pub async fn replay(&self, run_id: &str) -> FlowResult<RunResult> {
        let doc = self.store.load(run_id).await?;
        self.run_with_trigger(&doc.flow_name, doc.input, "replay").await
    }
}
