//! Postgres full-text index over docs entries. The filesystem (`.md` + `.mmd`)
//! remains the source of truth — this index is purely a search accelerator and
//! is reconstructible from the filesystem at any time (`rebuild_from_fs`).
//!
//! Lives in the shared platform DB `atelier_meta` (table `doc_entries`), the
//! same database used by the surveillance + control-plane subsystems. Search
//! uses a generated `tsvector` column + GIN index (`websearch_to_tsquery`,
//! `ts_rank_cd`, `ts_headline`) in place of the former SQLite FTS5/bm25.

use std::path::PathBuf;

use tracing::{info, warn};

// Local sqlx shim, mirroring atelier-watcher / atelier-common (no full `sqlx`
// facade dep — each crate re-exports what it needs from sqlx-core/-postgres).
#[allow(unused_imports)]
pub(crate) mod sqlx {
    pub use sqlx_core::Error;
    pub use sqlx_core::executor::Executor;
    pub use sqlx_core::pool::Pool;
    pub use sqlx_core::query::query;
    pub use sqlx_core::row::Row;
    pub use sqlx_postgres::{PgPool, PgRow, Postgres};
}

use self::sqlx::{PgPool, PgRow, Row, query};

use crate::fs::{Store, StoreError, walk_entries};
use crate::model::{DocEntry, DocType};

#[derive(Debug, thiserror::Error)]
pub enum IndexError {
    #[error("postgres error: {0}")]
    Sqlx(#[from] sqlx_core::Error),
    #[error("store error: {0}")]
    Store(#[from] StoreError),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

/// One search hit returned by `Index::search`.
#[derive(Debug, Clone, serde::Serialize)]
pub struct SearchHit {
    pub app_id: String,
    pub doc_type: String,
    pub name: String,
    pub title: Option<String>,
    /// Relevance score (higher = better match; `ts_rank_cd`).
    pub score: f64,
    pub snippet: String,
    /// Which field matched: `title`, `summary`, or `body`.
    pub matched_field: String,
}

/// Postgres-backed docs search index over table `doc_entries` in `atelier_meta`.
///
/// Holds the shared control-plane pool. The previous SQLite implementation kept
/// a per-process `Connection`; here we share the platform pool so the docs index
/// participates in the same database as tasks + registries.
#[derive(Clone)]
pub struct Index {
    pool: PgPool,
}

impl Index {
    /// Build the index over the shared `atelier_meta` pool. The DDL (table
    /// `doc_entries` + GIN index) is applied by the control-plane migration, so
    /// nothing schema-related happens here.
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Build the index and, if it holds no rows, rebuild it from the filesystem
    /// at `docs_root`. Mirrors the former `open_or_rebuild` entry point.
    pub async fn new_or_rebuild(pool: PgPool, docs_root: impl Into<PathBuf>) -> Result<Self, IndexError> {
        let idx = Self::new(pool);
        let count = idx.count().await?;
        if count == 0 {
            info!("Docs index empty — rebuilding from filesystem");
            idx.rebuild_from_fs(&Store::new(docs_root)).await?;
        }
        Ok(idx)
    }

    pub async fn count(&self) -> Result<u64, IndexError> {
        let row = query("SELECT COUNT(*) AS n FROM doc_entries")
            .fetch_one(&self.pool)
            .await?;
        let n: i64 = row.get("n");
        Ok(n.max(0) as u64)
    }

    /// Rebuild the index from scratch using the filesystem store as source of truth.
    pub async fn rebuild_from_fs(&self, store: &Store) -> Result<u64, IndexError> {
        let entries = walk_entries(&store.root)?;
        query("DELETE FROM doc_entries").execute(&self.pool).await?;
        let mut indexed = 0u64;
        for (app_id, doc_type, name) in entries {
            match store.read_entry(&app_id, doc_type, &name) {
                Ok(entry) => {
                    self.upsert(&entry).await?;
                    indexed += 1;
                }
                Err(e) => warn!(
                    app_id, doc_type = doc_type.as_str(), name, error = %e,
                    "Failed to read entry while rebuilding docs index"
                ),
            }
        }
        info!(indexed, "Docs index rebuild complete");
        Ok(indexed)
    }

    /// Upsert a single entry into `doc_entries`. The `tsv` column is generated by
    /// Postgres, so we only write the source fields.
    pub async fn upsert(&self, entry: &DocEntry) -> Result<(), IndexError> {
        let fm = &entry.frontmatter;
        let code_refs = serde_json::to_value(&fm.code_refs).unwrap_or(serde_json::Value::Null);
        let links = serde_json::to_value(&fm.links).unwrap_or(serde_json::Value::Null);
        query(
            r#"
            INSERT INTO doc_entries
                (app_id, doc_type, name, title, summary, scope, parent_screen,
                 code_refs, links, has_diagram, body, updated_at)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
            ON CONFLICT (app_id, doc_type, name) DO UPDATE SET
                title         = EXCLUDED.title,
                summary       = EXCLUDED.summary,
                scope         = EXCLUDED.scope,
                parent_screen = EXCLUDED.parent_screen,
                code_refs     = EXCLUDED.code_refs,
                links         = EXCLUDED.links,
                has_diagram   = EXCLUDED.has_diagram,
                body          = EXCLUDED.body,
                updated_at    = EXCLUDED.updated_at
            "#,
        )
        .bind(&entry.app_id)
        .bind(entry.doc_type.as_str())
        .bind(&entry.name)
        .bind(&fm.title)
        .bind(&fm.summary)
        .bind(&fm.scope)
        .bind(&fm.parent_screen)
        .bind(&code_refs)
        .bind(&links)
        .bind(fm.diagram)
        .bind(&entry.body)
        .bind(parse_ts(fm.updated_at.as_deref()))
        .execute(&self.pool)
        .await?;
        Ok(())
    }

    pub async fn remove(&self, app_id: &str, doc_type: DocType, name: &str) -> Result<(), IndexError> {
        query("DELETE FROM doc_entries WHERE app_id = $1 AND doc_type = $2 AND name = $3")
            .bind(app_id)
            .bind(doc_type.as_str())
            .bind(name)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    pub async fn remove_app(&self, app_id: &str) -> Result<(), IndexError> {
        query("DELETE FROM doc_entries WHERE app_id = $1")
            .bind(app_id)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    /// Full-text search. If `app_id` is given, results are scoped to that app.
    /// `doc_type` optionally filters by type. Limit defaults to 20, capped at 100.
    pub async fn search(
        &self,
        query_str: &str,
        app_id: Option<&str>,
        doc_type: Option<DocType>,
        limit: Option<u32>,
    ) -> Result<Vec<SearchHit>, IndexError> {
        let limit = limit.unwrap_or(20).min(100) as i64;
        if query_str.trim().is_empty() {
            return Ok(Vec::new());
        }

        // `websearch_to_tsquery` is forgiving of arbitrary user input (no syntax
        // errors on `:`, `-`, quotes, etc.), matching the robustness the old
        // FTS5 sanitizer provided. `simple` config = no stemming, language-agnostic.
        let sql = r#"
            SELECT app_id, doc_type, name, title,
                   ts_rank_cd(tsv, websearch_to_tsquery('simple', $1)) AS score,
                   ts_headline('simple',
                       coalesce(title, '') || ' ' || coalesce(summary, '') || ' ' || body,
                       websearch_to_tsquery('simple', $1),
                       'StartSel=<mark>,StopSel=</mark>,MaxWords=18,MinWords=6,ShortWord=2') AS snippet
              FROM doc_entries
             WHERE tsv @@ websearch_to_tsquery('simple', $1)
               AND ($2::text IS NULL OR app_id = $2)
               AND ($3::text IS NULL OR doc_type = $3)
             ORDER BY score DESC
             LIMIT $4
        "#;
        let rows: Vec<PgRow> = query(sql)
            .bind(query_str)
            .bind(app_id)
            .bind(doc_type.map(|t| t.as_str()))
            .bind(limit)
            .fetch_all(&self.pool)
            .await?;
        Ok(rows.iter().map(row_to_hit).collect())
    }
}

fn row_to_hit(row: &PgRow) -> SearchHit {
    let score: f32 = row.get("score");
    SearchHit {
        app_id: row.get("app_id"),
        doc_type: row.get("doc_type"),
        name: row.get("name"),
        title: row.get("title"),
        score: score as f64,
        snippet: row.get("snippet"),
        matched_field: "fts".to_string(),
    }
}

/// Parse an ISO-8601 frontmatter timestamp into a `DateTime<Utc>` for the
/// `TIMESTAMPTZ` column. Returns `None` on absent/invalid input (column nullable).
fn parse_ts(s: Option<&str>) -> Option<chrono::DateTime<chrono::Utc>> {
    s.and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
        .map(|d| d.with_timezone(&chrono::Utc))
}
