//! `CallbackRouter` builder used by Rust apps to expose `#[flow_action]`
//! functions and custom connectors over HTTP.
//!
//! The router is intentionally **not** generic over the app's state — its
//! handlers don't need state, only the in-memory action / connector registry.
//! `into_router::<S>()` is generic at materialisation time so the result can
//! be `merge`d into the app's `Router<S>` for any user state type.

use std::collections::HashMap;
use std::sync::Arc;

use axum::{
    extract::{Json, Path},
    middleware,
    routing::post,
    Router,
};
use hr_flow::{Connector, FlowError, FlowResult};
use serde_json::{json, Value};
use tracing::warn;

use crate::auth::{require_bearer, CallbackBearer};
use crate::handler::{action_handler, connector_handler, ActionHandler, CallbackBody};

#[derive(Clone)]
struct CallbackRegistry {
    actions: Arc<HashMap<String, ActionHandler>>,
    connectors: Arc<HashMap<String, Arc<dyn Connector>>>,
}

pub struct CallbackRouter {
    bearer: String,
    actions: HashMap<String, ActionHandler>,
    connectors: HashMap<String, Arc<dyn Connector>>,
}

impl CallbackRouter {
    pub fn new(_state: (), bearer: String) -> Self {
        Self::with_bearer(bearer)
    }

    pub fn with_bearer(bearer: String) -> Self {
        Self {
            bearer,
            actions: HashMap::new(),
            connectors: HashMap::new(),
        }
    }

    /// Register a single action handler. Most apps use `with_action(...)`
    /// chained against the macro-generated `mount_<fn>` instead.
    pub fn with_action_fn<F, Fut>(mut self, name: impl Into<String>, f: F) -> Self
    where
        F: Fn(Value) -> Fut + Clone + Send + Sync + 'static,
        Fut: std::future::Future<Output = FlowResult<Value>> + Send + 'static,
    {
        let h: ActionHandler = Arc::new(move |v| {
            let f = f.clone();
            Box::pin(f(v))
        });
        self.actions.insert(name.into(), h);
        self
    }

    /// Apply a `mount_<fn>` generated by the `#[flow_action]` macro.
    pub fn with_action<MountFn>(self, mount: MountFn) -> Self
    where
        MountFn: FnOnce(Self) -> Self,
    {
        mount(self)
    }

    pub fn with_connector(mut self, name: impl Into<String>, c: Arc<dyn Connector>) -> Self {
        self.connectors.insert(name.into(), c);
        self
    }

    /// Materialise into an `axum::Router<S>`, ready to be merged into the
    /// app's main router. The state type is chosen by the caller so the
    /// returned router is mergeable wherever needed.
    pub fn into_router<S>(self) -> Router<S>
    where
        S: Clone + Send + Sync + 'static,
    {
        let registry = CallbackRegistry {
            actions: Arc::new(self.actions),
            connectors: Arc::new(self.connectors),
        };
        let bearer_state = CallbackBearer {
            bearer: Arc::new(self.bearer),
        };

        Router::<S>::new()
            .route(
                "/_flow/action/{name}",
                post({
                    let registry = registry.clone();
                    move |path, body| dispatch_action(registry.clone(), path, body)
                }),
            )
            .route(
                "/_flow/connector/{name}/{op}",
                post({
                    let registry = registry.clone();
                    move |path, body| dispatch_connector(registry.clone(), path, body)
                }),
            )
            .layer(middleware::from_fn_with_state(bearer_state, require_bearer))
    }
}

async fn dispatch_action(
    registry: CallbackRegistry,
    Path(name): Path<String>,
    Json(body): Json<CallbackBody>,
) -> Json<Value> {
    let handler = match registry.actions.get(&name) {
        Some(h) => h.clone(),
        None => {
            warn!(action = %name, "callback action not registered");
            return Json(json!({
                "error": FlowError::UnknownAction(name.clone()).to_string(),
                "kind": "unknown_action",
            }));
        }
    };
    action_handler(Path(name), handler, body).await
}

async fn dispatch_connector(
    registry: CallbackRegistry,
    Path((name, op)): Path<(String, String)>,
    Json(body): Json<CallbackBody>,
) -> Json<Value> {
    let connector = match registry.connectors.get(&name) {
        Some(c) => c.clone(),
        None => {
            warn!(connector = %name, "callback connector not registered");
            return Json(json!({
                "error": FlowError::UnknownConnector(name.clone()).to_string(),
                "kind": "unknown_connector",
            }));
        }
    };
    connector_handler(Path((name, op)), connector, body).await
}
